# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wf2gKZ1KMlNUW57GbgVmaqDi2Q6o3YQa
"""

from tabulate import tabulate
import pandas as pd

thisdict = dict(name = "John", age = 36, country = "Norway")

print(thisdict)

workingHours = []
employeeName = ''
employees = ['Valentina', 'Jorge', 'Linda', 'Frank']
day = ''
hours = []
daysOfTheWeek = [ 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
scheduleForEmp = dict(employeeName= ' ', workingHours =  ' ', day = ' ' )

class Department:
   numberOfEmployees = int()
   numberOfHours = int()
   hoursOfOperation = {500,2200}
   def _init_(self,numberOfEmployees,numberOfHours,hoursOfOperation):
     self.numberOfEmployees = numberOfEmployees
     self.numberOfHours = numberOfHours
     self.hoursOfOperation = hoursOfOperation
   def _str_(self):
      return f"{self.numberOfEmployees,self.hoursOfOperation, self.numberOfHours}"

deli = Department( )
employeeCount = deli.numberOfEmployees = 6
hours=deli.numberOfhours = 235

class Employee:
  def _int_(self, employeeName, employeeHourRestriction):
    self.employeeHourRestriction = employeeHourRestriction
    self.employeeName = employeeName
  def _str_(self):
    return f"{self.employeeName, self.employeeHourRestriction}"

from unicodedata import name
valentina = Employee()
valentina.employeeName = 'Valentina'
valentina.employeeHourRestriction = {daysOfTheWeek[0] :[500,1800], daysOfTheWeek[1]:[500,1800], daysOfTheWeek[2]: [500,1800], daysOfTheWeek[3]:[500,1800], daysOfTheWeek[4]:[500,1800], daysOfTheWeek[5]: [500,1800], daysOfTheWeek[6]:[500,1800]}
linda = Employee()
linda.employeeName = 'Linda'
linda.employeeHourRestriction =  {daysOfTheWeek[0] :[500,1400] , daysOfTheWeek[1]:[500,1400], daysOfTheWeek[2]: [500,1400], daysOfTheWeek[3]:[500,1400], daysOfTheWeek[4]:[500,1400], daysOfTheWeek[5]: [500,1400], daysOfTheWeek[6]:[500,1400]}
frank = Employee()
frank.employeeName = 'Frank'
frank.employeeHourRestriction =  {daysOfTheWeek[0] :[1000,2200] , daysOfTheWeek[1]:[1000,2200], daysOfTheWeek[2]: [1000,2200], daysOfTheWeek[3]:[1000,2200], daysOfTheWeek[4]:[1000,2200], daysOfTheWeek[5]: [1000,2200], daysOfTheWeek[6]:[1000,2200]}
jorge = Employee()
jorge.employeeName = 'Jorge'
jorge.employeeHourRestriction = {daysOfTheWeek[0] :[1200,2200] , daysOfTheWeek[1]:[1200,2200], daysOfTheWeek[2]: [1200,2200], daysOfTheWeek[3]:[1200,2200], daysOfTheWeek[4]:[1200,2200], daysOfTheWeek[5]: [1200,2200], daysOfTheWeek[6]:[1200,2200]}



employeePool = []
employeePool.append(valentina)
employeePool.append(linda)
employeePool.append(frank)
employeePool.append(jorge)
print(employeePool[0].employeeHourRestriction)

i = 0
while i < len(employeePool):
  data_frame = pd.DataFrame(employeePool[i].employeeHourRestriction,columns=daysOfTheWeek)
  print(data_frame)

  i+=1

ii = 0
print(len(employeePool))
while ii < len(employeePool):
  table = tabulate(employeePool[ii].employeeHourRestriction,headers=daysOfTheWeek, tablefmt='fancy_grid')
  print(table)
  ii+=1
print(table)